debug: true # Debug enables PProf
locale: en

database:
  host: postgres
  user: gofiber-boilerplate
  password: gofiber-boilerplate
  dbname: gofiber-boilerplate
  port: 5432
  timezone: UTC
  sslmode: false
  logfile: ./log/db.log

# supported logging - debug, info, warning, error
logging:
  level: info # Logger instance used in API
  console: true # Console logging
  file: ./log/requestdecomposer.log

http:
  prefork: false
  address: :4000 # HTTP Address
